*** Settings ***
Resource   ../Justice_Keywords/APIKeywords.robot
Resource   ../Justice_Keywords/CommonKeywords.robot
Resource   ../Justice_Keywords/EventFiltersKeywords.robot
Resource   ../Justice_Keywords/ListFiltersKeywords.robot
Resource   ../Justice_Keywords/LoginKeywords.robot
Resource   ../Justice_Keywords/MonitorKeywords.robot
Resource   ../Justice_Keywords/MonitorListKeywords.robot
Resource   ../Justice_Keywords/MonitorListDeviceDetailsKeywords.robot
Resource   ../Justice_Keywords/MonitorListDevicesKeywords.robot
Resource   ../Justice_Keywords/MonitorListEventsKeywords.robot
Resource   ../Justice_Keywords/MonitorListEndSystemsKeywords.robot
Resource   ../Justice_Keywords/MonitorMapKeywords.robot
Resource   ../Justice_Keywords/ReportsKeywords.robot
Resource   ../Justice_Keywords/ReportsAnalyticsQuarterlySummaryKeywords.robot
Resource   ../Justice_Keywords/ReportsAnalyticsSummaryKeywords.robot
Resource   ../Justice_Keywords/ReportsDeviceAvailabilityKeywords.robot
Resource   ../Justice_Keywords/ReportsDeviceOverviewKeywords.robot
Resource   ../Justice_Keywords/ReportsEndSystemsKeywords.robot
Resource   ../Justice_Keywords/ReportsFilterKeywords.robot
Resource   ../Justice_Keywords/ReportsMetricKeywords.robot
Resource   ../Justice_Keywords/ReportsMetricPortUtilizationKeywords.robot
Resource   ../Justice_Keywords/ReportsMetricRxBandwidthKeywords.robot
Resource   ../Justice_Keywords/ReportsMetricTotalBandwidthKeywords.robot
Resource   ../Justice_Keywords/ReportsMetricTxBandwidthKeywords.robot
Resource   ../Justice_Keywords/ReportsNetworkScorecardKeywords.robot
Resource   ../Justice_Keywords/ReportsNetworkSummaryKeywords.robot
Resource   ../Justice_Keywords/ReportsPortOverviewKeywords.robot
Resource   ../Justice_Keywords/ReportsSelfServiceKeywords.robot
Resource   ../Justice_Keywords/ReportsSiteAvailabilityKeywords.robot
Resource   ../Justice_Keywords/ReportsSitePortUtilizationKeywords.robot
Resource   ../Justice_Keywords/ReportsTopNDeviceAvailabilityKeywords.robot
Resource   ../Justice_Keywords/ReportsTopPortUtilizationKeywords.robot
Resource   ../Justice_Keywords/ReportsTopSiteAvailabilityKeywords.robot
Resource   ../Justice_Keywords/SettingsSecurityKeywords.robot
Resource   ../Justice_Keywords/SettingsUserGroupsKeywords.robot
Resource   ../Justice_Keywords/SidebarKeywords.robot
Resource   ../Justice_Keywords/TagsKeywords.robot
